baseURL = "https://arjunmahishi.com/"
languageCode = "en"
title = "ಅರ್ಜುನ್ ಮಹಿಷಿ"
theme = "color-your-world"
enableEmoji = true
enableInlineShortcodes = true
paginate = 10
googleAnalytics = "UA-41041173-4"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    # To make use of the custom Chroma, this should be false
    # The default is true
    noClasses = false


[params]
  
  # Site description
  description = "Arjun Mahishi's personal website"
  
  # Author
  author      = "Arjun Mahishi"
  authorDesc  = "Software engineer"
  
  # Shows a message in the footer about JavaScript being disabled
  # The default is false
  hasNoscriptNotice = true
  
  # Default path for images in posts
  # ie.: "content/some-post/img"
  # Can also be set PER PAGE
  # It can be used to reduce repetition
  # There's no default value
  imgPath = "img"
  
  # Default classes for markup image 
  # Modifies the default behavior of images placed via markdown
  # Can also be set PER PAGE via front matter
  # Available classes are: border and borderless
  # There's no default value
  markupImgClass = ""
  
  # This will append a separator (of your choice) along the site title to your <title>
  # ie.: | ❚ - – — • ⚫ 
  # You can disabled it PER PAGE by using "disableTitleSeparator" at front
  # matter or disable it entirely by commenting the line below
  titleSeparator = "|"
  
  [params.search]
  
    # Enable search form (at the post list)
    # The default value is false
    enable = true
  
    # Limit search results
    # The default value is 30
    maxResults = 15
    
    # Limit seach field input and pattern matching
    minLength = 2   # Default is 3
    maxLength = 42  # Default is 32
    
    # Optional placeholder for search field
    placeholder = "Search for stuff here..."
    

  [params.style]
  
    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = true

    # Disable the use of system settings (prefers-color-scheme)
    # The default is false
    ignoreSystemSettings = true

    # Accent colors for light and dark mode respectively
    lightAccent  = "#225670" # Default is "#225670"
    darkAccent   = "#1dbc91" # Default is "#dd587c"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie. Firefox)
    # There's no default value. Used here just as example
    presets = [ "#1f676b", "#f3a530", "#902b37", "#1dbc91", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]
    
    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = true
    
    # Keep anchor links hidden until it's focused/hovered
    # The default is false
    hideAnchors = true
    
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

    # CSS animation transition when changing colors
    # The default is ".5s ease"
    changeTransition = ".3s ease"
    
    
  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."
    
  [params.social.centralized]
    github        = [ "arjunmahishi" ]
    instagram     = [ "arjunmahishi" ]
    linkedin      = [ "arjun-mahishi-b18968126" ]
    medium        = [ "@arjunmahishi" ]
    twitter       = [ "arjunmahishi", "@arjunmahishi" ]
    youtube       = [ "UC9eTgNyhtPaVf7h-YEo-R2w" ]
    #entry         = [ "username", "label (optional)" ]
    
    # The "entry" here IS important. It's used to load the data.

  [params.social.decentralized]
  
    # The "entry" here ISN'T important. It's used for nothing.
    
    
[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true



[languages]

  [languages.en]
  
    languageName = "English"

    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "Music"
        weight = 1
        url = "https://www.youtube.com/channel/UC9eTgNyhtPaVf7h-YEo-R2w"

      [[languages.en.menu.main]]
        name = "Blog posts"
        weight = 2
        url = "/posts"

      [[languages.en.menu.main]]
        name = "vim-adventures"
        weight = 3
        url = "/vim-adventures"

